[package]
name = "synomyms"
version = "0.0.0"
authors = ["Yasuhiro Asaka <yasuhiro.asaka@grauwoelfchen.net>"]

[[bin]]
name = "synomyms"
path = "src/main.rs"

[dependencies]
rand = "0.5.0-pre.1"
thesaurus = { path = "../thesaurus" }
